#!/bin/bash

# Colores
blue='\e[1;34m'
green='\e[1;32m'

# Condicion de root
if [ "$(id -u)" != "0" ]; then
   echo "Ejecuta este script como Root (o usando sudo)."
   exit 1
fi

clear
# cambiar tanaño de la terminal
resize -s 35 100 > /dev/null

# Escoger tarjeta de red
printf "\e[1;34mTarjetas de red detectadas\e[1;34m\e"
echo -e $green
ip link show|grep ^[0-9]| grep -v lo|cut -f2 -d":"|sed 's/^[ t]*//'
echo -e $blue
read -p  'Escribe tu tarjeta de red: ' input

i="0"

clear
while [ $i -lt 1 ]
do

e="0"

red=$(ip link show $input | awk '/ether/ {print $2}')

# Banner
 echo -e '\e[1;32m
       _______                       
      /  |/  /___ ______                           \e[1;34mCambia la identidad de la \e[1;32m  
     / /|_/ / __ `/ ___/                           \e[1;34mtarjeta de red de tu dispositivo. \e[1;32m
    / /  / / /_/ / /__               
   /_/  /_/\__,_/\___/          
                                                    \e[1;31mMac Changer es creado\e[1;32m
    ________                                        \e[1;31mSolo para propositos educativos.\e[1;32m
   / ____/ /_  ____ _____  ____ ____  _____
  / /   / __ \/ __ `/ __ \/ __ `/ _ \/ ___/                          
 / /___/ / / / /_/ / / / / /_/ /  __/ /              \e[1;37mHerramienta mejorada por "@AnibalTlgram"      \e[1;32m 
 \____/_/ /_/\__,_/_/ /_/\__, /\___/_/               \e[1;37mDel grupo https://t.me/TheRealHacking \e[1;32m
                        /____/            

\e[1;33m
01. DELL COMPUTER                11. HP PRINTER              \e[1;36m Tu direccion Mac = '$red' \e[1;33m
02. APPLE LAPTOP                 12. CANON PRINTER           
03. HUAWEI ANDROID PHONE         13. SAMSUNG TV               21. Direccion Mac personalizada
04. XIAOMI ANDROID PHONE         14. TVT CAMERA		      
05. SONY ANDROID PHONE           15. ZTE ROUTER               22. Direccion Mac original
06. LG ANDROID PHONE             16. TP-LINK ROUTER           
07. SAMSUNG ANDROID PHONE        17. OXYGEN ROUTER	      23. Salir
08. IPOD                         18. SOLAR PANEL             
09. IPAD                         19. NITENDO DS                   
10. IPHONE                       20. SONY PLAYSTATION 4       
'
 
# Opciones
dell='1'
macbook='2'
huawei='3'
xiaomi='4' 
sony='5'
lg='6'
samsung='7'
ipod='8'
ipad='9'
iphone='10'
hpprinter='11'
canonprinter='12'
samsungtv='13'
tvtcamera='14'
zte='15'
tplink='16'
oxygen='17'
solarpanel='18'
nitendods='19'
ps4='20'
custommac='21'
originalmac='22'
exit='23'





read -p 'Escoge una opcion: '  x

# Acciones despues de escoger numero

if [ "$x" == "$dell" ]; then                    #dell

ifconfig $input down
macchanger $input -m  18:03:73:E9:FB:86 > /dev/null 
ifconfig $input up
service NetworkManager restart

elif [ "$x" == "$macbook" ]; then                    #macbook

ifconfig $input down
macchanger $input -m  00:1F:5B:C7:EE:2F > /dev/null 
ifconfig $input up
service NetworkManager restart

elif [ "$x" == "$huawei" ]; then                    #huawei

ifconfig $input down
macchanger $input -m  8C:EB:C6:15:43:A4 > /dev/null 
ifconfig $input up
service NetworkManager restart


elif [ "$x" == "$xiaomi" ]; then                    #xiaomi

ifconfig $input down
macchanger $input -m  EC:D0:9F:82:EE:3F > /dev/null 
ifconfig $input up
service NetworkManager restart


elif [ "$x" == "$sony" ]; then                    #sony

ifconfig $input down
macchanger $input -m  9C:5C:F9:3F:17:D1 > /dev/null 
ifconfig $input up
service NetworkManager restart

elif [ "$x" == "$lg" ]; then                    #lg

ifconfig $input down
macchanger $input -m  BC:F5:AC:FF:38:A6 > /dev/null 
ifconfig $input up
service NetworkManager restart

elif [ "$x" == "$samsung" ]; then                    #samsung

ifconfig $input down
macchanger $input -m  8C:F5:A3:CB:14:C6 > /dev/null 
ifconfig $input up
service NetworkManager restart

elif [ "$x" == "$ipod" ]; then                    #ipod

ifconfig $input down
macchanger $input -m  FC:D8:48:03:54:8C > /dev/null 
ifconfig $input up
service NetworkManager restart


elif [ "$x" == "$ipad" ]; then                    #ipad

ifconfig $input down
macchanger $input -m  04:15:52:AB:6B:A4 > /dev/null 
ifconfig $input up
service NetworkManager restart

elif [ "$x" == "$iphone" ]; then                    #iphone

ifconfig $input down
macchanger $input -m  28:A0:2B:EC:6F:93 > /dev/null 
ifconfig $input up
service NetworkManager restart

elif [ "$x" == "$hpprinter" ]; then                    #hpprinter

ifconfig $input down
macchanger $input -m  D8:9D:67:DA:2F:32 > /dev/null 
ifconfig $input up
service NetworkManager restart

elif [ "$x" == "$canonprinter" ]; then                    #canonprinter

ifconfig $input down
macchanger $input -m  00:00:85:D2:01:4A > /dev/null 
ifconfig $input up
service NetworkManager restart

elif [ "$x" == "$samsungtv" ]; then                    #samsungtv

ifconfig $input down
macchanger $input -m  F8:77:B8:0C:49:B1 > /dev/null 
ifconfig $input up
service NetworkManager restart

elif [ "$x" == "$tvtcamera" ]; then                    #tvtcamera

ifconfig $input down
macchanger $input -m  00:18:AE:63:81:70 > /dev/null 
ifconfig $input up
service NetworkManager restart

elif [ "$x" == "$zte" ]; then                    #zte

ifconfig $input down
macchanger $input -m  34:4D:EA:87:8A:F8 > /dev/null 
ifconfig $input up
service NetworkManager restart

elif [ "$x" == "$tplink" ]; then                    #tplink

ifconfig $input down
macchanger $input -m  00:14:78:53:01:D8 > /dev/null 
ifconfig $input up
service NetworkManager restart

elif [ "$x" == "$oxygen" ]; then                    #oxygen

ifconfig $input down
macchanger $input -m  00:1d:1c:06:b5:ee > /dev/null 
ifconfig $input up
service NetworkManager restart

elif [ "$x" == "$solarpanel" ]; then                    #solarpanel

ifconfig $input down
macchanger $input -m  00:27:02:04:06:08 > /dev/null 
ifconfig $input up
service NetworkManager restart

elif [ "$x" == "$nitendods" ]; then                    #nitendods

ifconfig $input down
macchanger $input -m  00:1D:BC:C9:CC:ED > /dev/null 
ifconfig $input up
service NetworkManager restart

elif [ "$x" == "$ps4" ]; then                    #ps4

ifconfig $input down
macchanger $input -m  F8:46:1C:0D:27:1B > /dev/null 
ifconfig $input up
service NetworkManager restart

elif [ "$x" == "$originalmac" ]; then                    #originalmac

ifconfig $input down
macchanger -p $input > /dev/null 
ifconfig $input up					  
service NetworkManager restart

# Mac personalizada

elif [ "$x" == "$custommac" ]; then                 #custommac   


read -p 'Escribe la direccion mac (ejemplo AA:AA:AA:AA:AA:AA): '  m



ifconfig $input down
macchanger $input -m $m > /dev/null 
ifconfig $input up
service NetworkManager restart

e=1

clear


elif [ "$x" == "$exit" ]; then                 #exit                      

exit 


fi



if [ "$e" == 0 ]; then


echo -e '\e[1;32m
Tu direcion MAC a sido cambiada satisfactoriamente
Espere..
\e[0m
'

sleep 3,2

clear


fi






done





















